version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cinema_notification_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    container_name: cinema_notification_postgres
    env_file:
      - docker/postgresql/list.env
    image: postgres:latest
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_notification_data:
